version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.2
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

jobs:
  #section_10_deploy_to_heroku:
   # <<: *defaults
    #steps:
     # - checkout
      #- run:
       #   name: Deploy to Heroku
        #  command: |
         #   git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  section_11_deploy_to_heroku_using_docker:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - setup_remote_docker:
        docker_layer_caching: true
      - run: docker login --username=$HEROKU_MAIL --password=$HEROKU_API__KEY registry.heroku.com
      - run:
          name: Setup Heroku CLI
          command: |
            wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name:  Build and push Image
          command: |
            heroku container:push web -a car_model
            heroku container:release web -a car_model
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - section_11_deploy_to_heroku_using_docker